MS Build Tools 2015 linker error
Microsoft's breaking changes for Visual Studio include moving several functions "inline" which causes linker failures unless these 2 libraries are added to deliver the exported symbols.

Without these, the link fails with:

libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol _vsnwprintf
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol vfprintf
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol __iob_func
build\lib.win-amd64-3.5\yara.cp35-win_amd64.pyd : fatal error LNK1120: 3 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

   Creating library build\temp.win-amd64-3.5\Release\yara.cp35-win_amd64.lib and
 object build\temp.win-amd64-3.5\Release\yara.cp35-win_amd64.exp
libeay64.lib(cryptlib.obj) : error LNK2001: unresolved external symbol __iob_func
build\lib.win-amd64-3.5\yara.cp35-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120